# Generated by Django 4.1.7 on 2023-03-14 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='codigoa',
            new_name='codigo_aluno',
        ),
        migrations.RenameField(
            model_name='presenca',
            old_name='codigo',
            new_name='codigo_adm',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='nome',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_aluno',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenca',
            name='data_adm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
